### PR TITLE
Add code of Home Page

### PR DESCRIPTION
**Pull request by Abdullah-0024**
write code of Home page html and css

### CODE REVIEW

**Review by l1f21bsse0152 — APPROVED** [review]
Good work bro keep it up

**Review by pzRWdhah7689 — COMMENTED** [review]
good work

**Review by pzRWdhah7689 — APPROVED** [review]
good work

**Review by Farhanhaiderucp — APPROVED** [review]
clean code

**Comment by Farhanhaiderucp** [comment]
good work

**Pull request merged**
